
  #ifndef XNETOBJ_HXX_
  #define XNETOBJ_HXX_

  /**
   * @file
   * @author src/net/generate.tcl
   * @brief Autogenerated. Do not edit!
   */

  #include "../object_geraet.hxx"



class EnergyCharge;

class INO_EnergyCharge: public ImportedGameObject {
  NetworkConnection* cxn;
public:
  INO_EnergyCharge(NetworkConnection* cxn);
protected:
  virtual void construct() throw();
  virtual void update() throw();

private:
  EnergyCharge* decodeConstruct(const std::vector<byte>&) const throw();
  bool decodeUpdate(const std::vector<byte>&, EnergyCharge*) const throw();
};

class ENO_EnergyCharge: public ExportedGameObject {
public:
  ENO_EnergyCharge(NetworkConnection*, EnergyCharge*);

protected:
  virtual bool shouldUpdate() const throw();
  virtual void updateRemote() throw();

private:
  void encode() throw();
  EnergyCharge* clone(const EnergyCharge*) const throw();
};

#endif
