
  /**
   * @file
   * @author C++-Tcl Bridge Code Generator
   * @brief Autogenerated bindings; <b>not intended for human consumption</b>
   *
   * AUTOGENERATED BY generate.tcl. DO NOT EDIT DIRECTLY.
   * @see src/tcl_iface/readme.txt
   */

  #include <map>
  #include <set>
  #include <vector>
  #include <string>
  #include <cstring>
  #include <cstdio>
  #include <cstdlib>
  #include <iostream>

  #include <GL/gl.h>
  #include <SDL.h>
  #include <tcl.h>
  #include <itcl.h>
  #include <libconfig.h++>

  #include "src/tcl_iface/bridge.hxx"
  #include "src/tcl_iface/implementation.hxx"
  #include "src/tcl_iface/dynfun.hxx"
  #include "src/exit_conditions.hxx"
  #include "src/globals.hxx"

  #pragma GCC diagnostic ignored "-Wunused-label"
  #pragma GCC diagnostic ignored "-Waddress"
  using namespace std;
  using namespace tcl_glue_implementation;
  using namespace libconfig;

  //Commands get their zeroth argument as their own name;
  //code generation is simpler if we drop this
  #define SHIFT ++objv, --objc

class Ship;
class NetworkConnection;
class InputNetworkGeraet;
int trampoline1(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline3(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline5(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline7(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline9(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline11(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline13(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline15(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline17(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline19(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline21(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline23(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline25(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline27(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline29(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline31(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline33(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline35(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline37(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline39(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline41(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline43(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline45(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline47(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline49(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline51(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline53(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline55(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline57(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get59(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline61(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get63(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get65(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get67(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get69(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get71(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get73(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get75(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get77(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get79(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get81(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get83(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get85(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get87(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec89(bool,Tcl_Interp*) throw();
void classdec102(bool,Tcl_Interp*) throw();
int get112(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get114(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get116(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get118(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get120(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline122(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get124(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get126(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline128(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec130(bool,Tcl_Interp*) throw();
void classdec149(bool,Tcl_Interp*) throw();
int trampoline168(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline170(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline172(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int get174(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get176(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get178(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set179(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline181(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec183(bool,Tcl_Interp*) throw();
int get204(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get206(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec208(bool,Tcl_Interp*) throw();
void classdec223(bool,Tcl_Interp*) throw();

int get226(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set227(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get229(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set230(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get232(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set233(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get235(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set236(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec238(bool,Tcl_Interp*) throw();

void classdec245(bool,Tcl_Interp*) throw();
void classdec246(bool,Tcl_Interp*) throw();
void classdec321(bool,Tcl_Interp*) throw();
void classdec322(bool,Tcl_Interp*) throw();
void classdec359(bool,Tcl_Interp*) throw();
void classdec394(bool,Tcl_Interp*) throw();
void classdec401(bool,Tcl_Interp*) throw();
void classdec408(bool,Tcl_Interp*) throw();

void classdec432(bool,Tcl_Interp*) throw();

void classdec441(bool,Tcl_Interp*) throw();

void classdec454(bool,Tcl_Interp*) throw();
void classdec455(bool,Tcl_Interp*) throw();
void classdec456(bool,Tcl_Interp*) throw();
void classdec457(bool,Tcl_Interp*) throw();
void classdec458(bool,Tcl_Interp*) throw();

void classdec459(bool,Tcl_Interp*) throw();
void classdec468(bool,Tcl_Interp*) throw();
int trampoline471(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
void classdec473(bool,Tcl_Interp*) throw();
int trampoline603(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
void classdec605(bool,Tcl_Interp*) throw();
int trampoline610(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline612(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline614(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline616(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec618(bool,Tcl_Interp*) throw();

int trampoline637(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline639(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline641(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline643(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec645(bool,Tcl_Interp*) throw();
void classdec658(bool,Tcl_Interp*) throw();
void classdec671(bool,Tcl_Interp*) throw();
void classdec674(bool,Tcl_Interp*) throw();
void classdec685(bool,Tcl_Interp*) throw();
void classdec688(bool,Tcl_Interp*) throw();
void classdec691(bool,Tcl_Interp*) throw();
int get700(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec702(bool,Tcl_Interp*) throw();

void classdec711(bool,Tcl_Interp*) throw();

void classdec714(bool,Tcl_Interp*) throw();
int trampoline717(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec719(bool,Tcl_Interp*) throw();

void classdec736(bool,Tcl_Interp*) throw();

void classdec752(bool,Tcl_Interp*) throw();

void classdec777(bool,Tcl_Interp*) throw();

void classdec780(bool,Tcl_Interp*) throw();

void classdec793(bool,Tcl_Interp*) throw();
int get806(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get808(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set809(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int trampoline811(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline813(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec815(bool,Tcl_Interp*) throw();

void classdec820(bool,Tcl_Interp*) throw();
int trampoline833(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
void classdec835(bool,Tcl_Interp*) throw();
int trampoline844(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec846(bool,Tcl_Interp*) throw();

void classdec867(bool,Tcl_Interp*) throw();
void classdec870(bool,Tcl_Interp*) throw();
void classdec885(bool,Tcl_Interp*) throw();

void classdec906(bool,Tcl_Interp*) throw();

int get951(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get953(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec955(bool,Tcl_Interp*) throw();
int trampoline1054(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1056(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1058(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1060(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1062(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1064(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1066(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1068(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1070(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1072(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get1074(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1075(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1077(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1079(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1081(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1083(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1085(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1086(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1088(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1089(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1091(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1092(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1094(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1095(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1097(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1098(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1100(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1102(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1103(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1105(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1106(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1108(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1109(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1111(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1112(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1114(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1115(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1117(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1118(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1120(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1121(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1123(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1124(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1126(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1127(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1129(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1130(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1132(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1133(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1135(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1137(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1139(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1141(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1143(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1145(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1147(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec1149(bool,Tcl_Interp*) throw();

void classdec1162(bool,Tcl_Interp*) throw();
void classdec1163(bool,Tcl_Interp*) throw();
void classdec1164(bool,Tcl_Interp*) throw();
int get1184(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1186(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1187(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

void classdec1189(bool,Tcl_Interp*) throw();

void classdec1192(bool,Tcl_Interp*) throw();

void classdec1197(bool,Tcl_Interp*) throw();
void classdec1198(bool,Tcl_Interp*) throw();

void classdec1199(bool,Tcl_Interp*) throw();

void classdec1224(bool,Tcl_Interp*) throw();
void classdec1225(bool,Tcl_Interp*) throw();

void classdec1241(bool,Tcl_Interp*) throw();

void classdec1242(bool,Tcl_Interp*) throw();
void classdec1243(bool,Tcl_Interp*) throw();

void classdec1244(bool,Tcl_Interp*) throw();

void classdec1253(bool,Tcl_Interp*) throw();

void classdec1256(bool,Tcl_Interp*) throw();

void classdec1265(bool,Tcl_Interp*) throw();

void classdec1274(bool,Tcl_Interp*) throw();

void classdec1275(bool,Tcl_Interp*) throw();
void classdec1280(bool,Tcl_Interp*) throw();

void classdec1285(bool,Tcl_Interp*) throw();
void classdec1300(bool,Tcl_Interp*) throw();
void classdec1329(bool,Tcl_Interp*) throw();

void classdec1386(bool,Tcl_Interp*) throw();
int get1481(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline1483(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1485(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1487(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1489(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1491(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1493(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1495(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1497(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1499(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1501(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1503(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1505(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1507(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1509(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1511(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1513(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1515(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1517(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1519(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1521(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1523(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1525(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1527(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1529(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec1531(bool,Tcl_Interp*) throw();

int trampoline1534(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1536(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1538(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1540(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1542(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1544(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec1546(bool,Tcl_Interp*) throw();
int trampoline1551(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1553(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1555(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1557(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();


  Tcl_Interp* newInterpreter(bool safe, Tcl_Interp* master) {
    Tcl_Interp* interp = newInterpreterImpl(safe,master);
    //Autodecs follow

Tcl_CreateObjCommand(interp, "c++ trampoline1", trampoline1, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline3", trampoline3, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline5", trampoline5, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline7", trampoline7, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline9", trampoline9, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline11", trampoline11, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline13", trampoline13, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline15", trampoline15, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline17", trampoline17, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline19", trampoline19, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline21", trampoline21, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline23", trampoline23, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline25", trampoline25, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline27", trampoline27, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline29", trampoline29, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline31", trampoline31, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline33", trampoline33, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline35", trampoline35, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline37", trampoline37, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline39", trampoline39, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline41", trampoline41, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline43", trampoline43, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline45", trampoline45, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline47", trampoline47, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline49", trampoline49, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline51", trampoline51, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline53", trampoline53, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline55", trampoline55, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline57", trampoline57, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get59", get59, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline61", trampoline61, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get63", get63, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get65", get65, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get67", get67, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get69", get69, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get71", get71, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get73", get73, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get75", get75, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get77", get77, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get79", get79, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get81", get81, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get83", get83, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get85", get85, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get87", get87, 0, NULL);
classdec89(safe, interp);
classdec102(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get112", get112, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get114", get114, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get116", get116, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get118", get118, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get120", get120, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline122", trampoline122, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get124", get124, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get126", get126, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline128", trampoline128, 0, NULL);
}
classdec130(safe, interp);
classdec149(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline168", trampoline168, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline170", trampoline170, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline172", trampoline172, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get174", get174, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get176", get176, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get178", get178, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set179", set179, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline181", trampoline181, 0, NULL);
}
classdec183(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get204", get204, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get206", get206, 0, NULL);
classdec208(safe, interp);
if (!safe) {
classdec223(safe, interp);
}
Tcl_CreateObjCommand(interp, "c++ get226", get226, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set227", set227, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get229", get229, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set230", set230, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get232", get232, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set233", set233, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get235", get235, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set236", set236, 0, NULL);
if (!safe) {
classdec238(safe, interp);
}

classdec246(safe, interp);

classdec322(safe, interp);
classdec359(safe, interp);
classdec394(safe, interp);
classdec401(safe, interp);
if (!safe) {
classdec408(safe, interp);
}
if (!safe) {
classdec432(safe, interp);
}
if (!safe) {
classdec441(safe, interp);
}





{
      TypeExport* ex=new TypeExport(typeid(DynFun2<void,Ship*,bool>::fun_t));
      ex->isAObject=false;
      ex->tclClassName = "fun<void:Ship*,bool>::fun_t";
      typeExports[&typeid(DynFun2<void,Ship*,bool>::fun_t)]=ex;
    }
classdec459(safe, interp);
classdec468(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline471", trampoline471, 0, NULL);
classdec473(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline603", trampoline603, 0, NULL);
classdec605(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline610", trampoline610, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline612", trampoline612, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline614", trampoline614, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline616", trampoline616, 0, NULL);
}
if (!safe) {
classdec618(safe, interp);
}
Tcl_CreateObjCommand(interp, "c++ trampoline637", trampoline637, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline639", trampoline639, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline641", trampoline641, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline643", trampoline643, 0, NULL);
}
classdec645(safe, interp);
classdec658(safe, interp);
classdec671(safe, interp);
classdec674(safe, interp);
classdec685(safe, interp);
classdec688(safe, interp);
classdec691(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get700", get700, 0, NULL);
if (!safe) {
classdec702(safe, interp);
}
if (!safe) {
classdec711(safe, interp);
}
if (!safe) {
classdec714(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline717", trampoline717, 0, NULL);
}
if (!safe) {
classdec719(safe, interp);
}
if (!safe) {
classdec736(safe, interp);
}
if (!safe) {
classdec752(safe, interp);
}
if (!safe) {
classdec777(safe, interp);
}
if (!safe) {
classdec780(safe, interp);
}
if (!safe) {
classdec793(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get806", get806, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get808", get808, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set809", set809, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline811", trampoline811, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline813", trampoline813, 0, NULL);
}
if (!safe) {
classdec815(safe, interp);
}
if (!safe) {
classdec820(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline833", trampoline833, 0, NULL);
classdec835(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline844", trampoline844, 0, NULL);
}
if (!safe) {
classdec846(safe, interp);
}
classdec867(safe, interp);
classdec870(safe, interp);
if (!safe) {
classdec885(safe, interp);
}
if (!safe) {
classdec906(safe, interp);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get951", get951, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get953", get953, 0, NULL);
classdec955(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline1054", trampoline1054, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1056", trampoline1056, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1058", trampoline1058, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1060", trampoline1060, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1062", trampoline1062, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1064", trampoline1064, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1066", trampoline1066, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1068", trampoline1068, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1070", trampoline1070, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1072", trampoline1072, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1074", get1074, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1075", set1075, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1077", get1077, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1079", get1079, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1081", get1081, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1083", get1083, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1085", get1085, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1086", set1086, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1088", get1088, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1089", set1089, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1091", get1091, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1092", set1092, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1094", get1094, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1095", set1095, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1097", get1097, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1098", set1098, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1100", get1100, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1102", get1102, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1103", set1103, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1105", get1105, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1106", set1106, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1108", get1108, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1109", set1109, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1111", get1111, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1112", set1112, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1114", get1114, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1115", set1115, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1117", get1117, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1118", set1118, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1120", get1120, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1121", set1121, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1123", get1123, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1124", set1124, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1126", get1126, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1127", set1127, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1129", get1129, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1130", set1130, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1132", get1132, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1133", set1133, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1135", get1135, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1137", get1137, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1139", get1139, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1141", get1141, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1143", get1143, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1145", get1145, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1147", get1147, 0, NULL);
if (!safe) {
classdec1149(safe, interp);
}
if (!safe) {


classdec1164(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get1184", get1184, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1186", get1186, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1187", set1187, 0, NULL);
}
if (!safe) {
classdec1189(safe, interp);
}
if (!safe) {
classdec1192(safe, interp);
}
if (!safe) {
classdec1197(safe, interp);

}
if (!safe) {
classdec1199(safe, interp);
}
if (!safe) {

classdec1225(safe, interp);
}
if (!safe) {
classdec1241(safe, interp);
}
if (!safe) {
classdec1242(safe, interp);
classdec1243(safe, interp);
{
      TypeExport* ex=new TypeExport(typeid(DynFun1<InputNetworkGeraet*,NetworkConnection*>::fun_t));
      ex->isAObject=false;
      ex->tclClassName = "fun<InputNetworkGeraet*:NetworkConnection*>::fun_t";
      typeExports[&typeid(DynFun1<InputNetworkGeraet*,NetworkConnection*>::fun_t)]=ex;
    }
classdec1244(safe, interp);
}
if (!safe) {
classdec1253(safe, interp);
}
if (!safe) {
classdec1256(safe, interp);
}
if (!safe) {
classdec1265(safe, interp);
}
if (!safe) {

}
if (!safe) {
classdec1275(safe, interp);
classdec1280(safe, interp);
}
if (!safe) {
classdec1285(safe, interp);
classdec1300(safe, interp);
classdec1329(safe, interp);
}
classdec1386(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get1481", get1481, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1483", trampoline1483, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1485", trampoline1485, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1487", trampoline1487, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1489", trampoline1489, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1491", trampoline1491, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1493", trampoline1493, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1495", trampoline1495, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1497", trampoline1497, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1499", trampoline1499, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1501", trampoline1501, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1503", trampoline1503, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1505", trampoline1505, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1507", trampoline1507, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1509", trampoline1509, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1511", trampoline1511, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1513", trampoline1513, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1515", trampoline1515, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1517", trampoline1517, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1519", trampoline1519, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1521", trampoline1521, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1523", trampoline1523, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1525", trampoline1525, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1527", trampoline1527, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1529", trampoline1529, 0, NULL);
}
if (!safe) {
classdec1531(safe, interp);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1534", trampoline1534, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1536", trampoline1536, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1538", trampoline1538, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1540", trampoline1540, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1542", trampoline1542, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1544", trampoline1544, 0, NULL);
}
classdec1546(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline1551", trampoline1551, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1553", trampoline1553, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1555", trampoline1555, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1557", trampoline1557, 0, NULL);
}
newInterpreterImplPost(interp);
invokingInterpreter=master;
return interp; }
