
  /**
   * @file
   * @author C++-Tcl Bridge Code Generator
   * @brief Autogenerated bindings; <b>not intended for human consumption</b>
   *
   * AUTOGENERATED BY generate.tcl. DO NOT EDIT DIRECTLY.
   * @see src/tcl_iface/readme.txt
   */

  #include <map>
  #include <set>
  #include <vector>
  #include <string>
  #include <cstring>
  #include <cstdio>
  #include <cstdlib>
  #include <iostream>

  #include <GL/gl.h>
  #include <SDL.h>
  #include <tcl.h>
  #include <itcl.h>
  #include <libconfig.h++>

  #include "src/tcl_iface/bridge.hxx"
  #include "src/tcl_iface/implementation.hxx"
  #include "src/tcl_iface/dynfun.hxx"
  #include "src/exit_conditions.hxx"
  #include "src/globals.hxx"

  #pragma GCC diagnostic ignored "-Wunused-label"
  #pragma GCC diagnostic ignored "-Waddress"
  using namespace std;
  using namespace tcl_glue_implementation;
  using namespace libconfig;

  //Commands get their zeroth argument as their own name;
  //code generation is simpler if we drop this
  #define SHIFT ++objv, --objc

class Ship;
class NetworkConnection;
class InputNetworkGeraet;
int trampoline1(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline3(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline5(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline7(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline9(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline11(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline13(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline15(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline17(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline19(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline21(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline23(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline25(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline27(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline29(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline31(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline33(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline35(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline37(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline39(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline41(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline43(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline45(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline47(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline49(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline51(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline53(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline55(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline57(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get59(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get61(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get63(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get65(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get67(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get69(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get71(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get73(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get75(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get77(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get79(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get81(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get83(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec85(bool,Tcl_Interp*) throw();
void classdec98(bool,Tcl_Interp*) throw();
int get108(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get110(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get112(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get114(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get116(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline118(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get120(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get122(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline124(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec126(bool,Tcl_Interp*) throw();
void classdec145(bool,Tcl_Interp*) throw();
int trampoline164(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline166(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec168(bool,Tcl_Interp*) throw();
int get189(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get191(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec193(bool,Tcl_Interp*) throw();
void classdec208(bool,Tcl_Interp*) throw();

int get211(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set212(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get214(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set215(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get217(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set218(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get220(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set221(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec223(bool,Tcl_Interp*) throw();

void classdec230(bool,Tcl_Interp*) throw();
void classdec231(bool,Tcl_Interp*) throw();
void classdec314(bool,Tcl_Interp*) throw();
void classdec315(bool,Tcl_Interp*) throw();
void classdec350(bool,Tcl_Interp*) throw();
void classdec385(bool,Tcl_Interp*) throw();
void classdec392(bool,Tcl_Interp*) throw();
void classdec399(bool,Tcl_Interp*) throw();

void classdec423(bool,Tcl_Interp*) throw();

void classdec432(bool,Tcl_Interp*) throw();

void classdec445(bool,Tcl_Interp*) throw();
void classdec446(bool,Tcl_Interp*) throw();
void classdec447(bool,Tcl_Interp*) throw();
void classdec448(bool,Tcl_Interp*) throw();
void classdec449(bool,Tcl_Interp*) throw();

void classdec450(bool,Tcl_Interp*) throw();
void classdec459(bool,Tcl_Interp*) throw();
void classdec462(bool,Tcl_Interp*) throw();
int trampoline590(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline592(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline594(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec596(bool,Tcl_Interp*) throw();

int trampoline615(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline617(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline619(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline621(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec623(bool,Tcl_Interp*) throw();
void classdec636(bool,Tcl_Interp*) throw();
void classdec649(bool,Tcl_Interp*) throw();
void classdec652(bool,Tcl_Interp*) throw();
void classdec663(bool,Tcl_Interp*) throw();
void classdec666(bool,Tcl_Interp*) throw();
void classdec669(bool,Tcl_Interp*) throw();
int get678(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec680(bool,Tcl_Interp*) throw();

void classdec689(bool,Tcl_Interp*) throw();

void classdec692(bool,Tcl_Interp*) throw();
int trampoline695(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec697(bool,Tcl_Interp*) throw();

void classdec714(bool,Tcl_Interp*) throw();

void classdec730(bool,Tcl_Interp*) throw();

void classdec755(bool,Tcl_Interp*) throw();

void classdec758(bool,Tcl_Interp*) throw();

void classdec771(bool,Tcl_Interp*) throw();
int get784(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int trampoline786(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline788(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec790(bool,Tcl_Interp*) throw();

void classdec795(bool,Tcl_Interp*) throw();
int trampoline808(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
void classdec810(bool,Tcl_Interp*) throw();
int trampoline819(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

void classdec821(bool,Tcl_Interp*) throw();

void classdec842(bool,Tcl_Interp*) throw();
void classdec845(bool,Tcl_Interp*) throw();
void classdec860(bool,Tcl_Interp*) throw();

void classdec881(bool,Tcl_Interp*) throw();

int get926(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get928(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec930(bool,Tcl_Interp*) throw();
int trampoline1029(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1031(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1033(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1035(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1037(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1039(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1041(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1043(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1045(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1047(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int get1049(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1050(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1052(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1054(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1056(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1058(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1060(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1061(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1063(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1064(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1066(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1067(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1069(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1070(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1072(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1073(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1075(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1077(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1078(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1080(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1081(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1083(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1084(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1086(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1087(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1089(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1090(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1092(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1093(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1095(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1096(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1098(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1099(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1101(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1102(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1104(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1105(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1107(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1108(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

int get1110(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1112(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1114(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1116(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1118(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1120(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
void classdec1122(bool,Tcl_Interp*) throw();

void classdec1135(bool,Tcl_Interp*) throw();
void classdec1136(bool,Tcl_Interp*) throw();
void classdec1137(bool,Tcl_Interp*) throw();
int get1157(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int get1159(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);int set1160(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);

void classdec1162(bool,Tcl_Interp*) throw();

void classdec1165(bool,Tcl_Interp*) throw();

void classdec1170(bool,Tcl_Interp*) throw();
void classdec1171(bool,Tcl_Interp*) throw();

void classdec1172(bool,Tcl_Interp*) throw();

void classdec1195(bool,Tcl_Interp*) throw();

void classdec1206(bool,Tcl_Interp*) throw();

void classdec1207(bool,Tcl_Interp*) throw();

void classdec1216(bool,Tcl_Interp*) throw();

void classdec1227(bool,Tcl_Interp*) throw();
void classdec1228(bool,Tcl_Interp*) throw();

void classdec1229(bool,Tcl_Interp*) throw();

void classdec1238(bool,Tcl_Interp*) throw();

void classdec1239(bool,Tcl_Interp*) throw();
void classdec1244(bool,Tcl_Interp*) throw();

void classdec1249(bool,Tcl_Interp*) throw();
int get1344(ClientData,Tcl_Interp*,int,Tcl_Obj*const[]);
int trampoline1346(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1348(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1350(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1352(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1354(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1356(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1358(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1360(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1362(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1364(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1366(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1368(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1370(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1372(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1374(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1376(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1378(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1380(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1382(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1384(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1386(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1388(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1390(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1392(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1394(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1396(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1398(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();
int trampoline1400(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();

int trampoline1402(ClientData,Tcl_Interp*,int,Tcl_Obj*const[])throw();


  Tcl_Interp* newInterpreter(bool safe, Tcl_Interp* master) {
    Tcl_Interp* interp = newInterpreterImpl(safe,master);
    //Autodecs follow

Tcl_CreateObjCommand(interp, "c++ trampoline1", trampoline1, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline3", trampoline3, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline5", trampoline5, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline7", trampoline7, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline9", trampoline9, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline11", trampoline11, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline13", trampoline13, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline15", trampoline15, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline17", trampoline17, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline19", trampoline19, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline21", trampoline21, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline23", trampoline23, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline25", trampoline25, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline27", trampoline27, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline29", trampoline29, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline31", trampoline31, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline33", trampoline33, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline35", trampoline35, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline37", trampoline37, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline39", trampoline39, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline41", trampoline41, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline43", trampoline43, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline45", trampoline45, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline47", trampoline47, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline49", trampoline49, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline51", trampoline51, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline53", trampoline53, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline55", trampoline55, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline57", trampoline57, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get59", get59, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get61", get61, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get63", get63, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get65", get65, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get67", get67, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get69", get69, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get71", get71, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get73", get73, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get75", get75, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get77", get77, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get79", get79, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get81", get81, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get83", get83, 0, NULL);
classdec85(safe, interp);
classdec98(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get108", get108, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get110", get110, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get112", get112, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get114", get114, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get116", get116, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline118", trampoline118, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get120", get120, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get122", get122, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline124", trampoline124, 0, NULL);
}
classdec126(safe, interp);
classdec145(safe, interp);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline164", trampoline164, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline166", trampoline166, 0, NULL);
}
classdec168(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get189", get189, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get191", get191, 0, NULL);
classdec193(safe, interp);
if (!safe) {
classdec208(safe, interp);
}
Tcl_CreateObjCommand(interp, "c++ get211", get211, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set212", set212, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get214", get214, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set215", set215, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get217", get217, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set218", set218, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get220", get220, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set221", set221, 0, NULL);
if (!safe) {
classdec223(safe, interp);
}

classdec231(safe, interp);

classdec315(safe, interp);
classdec350(safe, interp);
classdec385(safe, interp);
classdec392(safe, interp);
if (!safe) {
classdec399(safe, interp);
}
if (!safe) {
classdec423(safe, interp);
}
if (!safe) {
classdec432(safe, interp);
}





{
      TypeExport* ex=new TypeExport(typeid(DynFun2<void,Ship*,bool>::fun_t));
      ex->isAObject=false;
      ex->tclClassName = "fun<void:Ship*,bool>::fun_t";
      typeExports[&typeid(DynFun2<void,Ship*,bool>::fun_t)]=ex;
    }
classdec450(safe, interp);
classdec459(safe, interp);
classdec462(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline590", trampoline590, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline592", trampoline592, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline594", trampoline594, 0, NULL);
}
if (!safe) {
classdec596(safe, interp);
}
Tcl_CreateObjCommand(interp, "c++ trampoline615", trampoline615, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline617", trampoline617, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline619", trampoline619, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline621", trampoline621, 0, NULL);
}
classdec623(safe, interp);
classdec636(safe, interp);
classdec649(safe, interp);
classdec652(safe, interp);
classdec663(safe, interp);
classdec666(safe, interp);
classdec669(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get678", get678, 0, NULL);
if (!safe) {
classdec680(safe, interp);
}
if (!safe) {
classdec689(safe, interp);
}
if (!safe) {
classdec692(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline695", trampoline695, 0, NULL);
}
if (!safe) {
classdec697(safe, interp);
}
if (!safe) {
classdec714(safe, interp);
}
if (!safe) {
classdec730(safe, interp);
}
if (!safe) {
classdec755(safe, interp);
}
if (!safe) {
classdec758(safe, interp);
}
if (!safe) {
classdec771(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get784", get784, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline786", trampoline786, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline788", trampoline788, 0, NULL);
}
if (!safe) {
classdec790(safe, interp);
}
if (!safe) {
classdec795(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline808", trampoline808, 0, NULL);
classdec810(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline819", trampoline819, 0, NULL);
}
if (!safe) {
classdec821(safe, interp);
}
classdec842(safe, interp);
classdec845(safe, interp);
if (!safe) {
classdec860(safe, interp);
}
if (!safe) {
classdec881(safe, interp);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get926", get926, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get928", get928, 0, NULL);
classdec930(safe, interp);
Tcl_CreateObjCommand(interp, "c++ trampoline1029", trampoline1029, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1031", trampoline1031, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1033", trampoline1033, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1035", trampoline1035, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1037", trampoline1037, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1039", trampoline1039, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1041", trampoline1041, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1043", trampoline1043, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1045", trampoline1045, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1047", trampoline1047, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1049", get1049, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1050", set1050, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1052", get1052, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1054", get1054, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1056", get1056, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1058", get1058, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1060", get1060, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1061", set1061, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1063", get1063, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1064", set1064, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1066", get1066, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1067", set1067, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1069", get1069, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1070", set1070, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1072", get1072, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1073", set1073, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1075", get1075, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ get1077", get1077, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1078", set1078, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1080", get1080, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1081", set1081, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1083", get1083, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1084", set1084, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1086", get1086, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1087", set1087, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1089", get1089, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1090", set1090, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1092", get1092, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1093", set1093, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1095", get1095, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1096", set1096, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1098", get1098, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1099", set1099, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1101", get1101, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1102", set1102, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1104", get1104, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1105", set1105, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1107", get1107, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1108", set1108, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ get1110", get1110, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1112", get1112, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1114", get1114, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1116", get1116, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1118", get1118, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1120", get1120, 0, NULL);
if (!safe) {
classdec1122(safe, interp);
}
if (!safe) {


classdec1137(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get1157", get1157, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ get1159", get1159, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ set1160", set1160, 0, NULL);
}
if (!safe) {
classdec1162(safe, interp);
}
if (!safe) {
classdec1165(safe, interp);
}
if (!safe) {
classdec1170(safe, interp);

}
if (!safe) {
classdec1172(safe, interp);
}
if (!safe) {
classdec1195(safe, interp);
}
if (!safe) {
classdec1206(safe, interp);
}
if (!safe) {
classdec1207(safe, interp);
}
if (!safe) {
classdec1216(safe, interp);
}
if (!safe) {
classdec1227(safe, interp);
classdec1228(safe, interp);
{
      TypeExport* ex=new TypeExport(typeid(DynFun1<InputNetworkGeraet*,NetworkConnection*>::fun_t));
      ex->isAObject=false;
      ex->tclClassName = "fun<InputNetworkGeraet*:NetworkConnection*>::fun_t";
      typeExports[&typeid(DynFun1<InputNetworkGeraet*,NetworkConnection*>::fun_t)]=ex;
    }
classdec1229(safe, interp);
}
if (!safe) {

}
if (!safe) {
classdec1239(safe, interp);
classdec1244(safe, interp);
}
classdec1249(safe, interp);
Tcl_CreateObjCommand(interp, "c++ get1344", get1344, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1346", trampoline1346, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1348", trampoline1348, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1350", trampoline1350, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1352", trampoline1352, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1354", trampoline1354, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1356", trampoline1356, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1358", trampoline1358, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1360", trampoline1360, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1362", trampoline1362, 0, NULL);
}
Tcl_CreateObjCommand(interp, "c++ trampoline1364", trampoline1364, 0, NULL);
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1366", trampoline1366, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1368", trampoline1368, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1370", trampoline1370, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1372", trampoline1372, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1374", trampoline1374, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1376", trampoline1376, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1378", trampoline1378, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1380", trampoline1380, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1382", trampoline1382, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1384", trampoline1384, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1386", trampoline1386, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1388", trampoline1388, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1390", trampoline1390, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1392", trampoline1392, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1394", trampoline1394, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1396", trampoline1396, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1398", trampoline1398, 0, NULL);
Tcl_CreateObjCommand(interp, "c++ trampoline1400", trampoline1400, 0, NULL);
}
if (!safe) {
Tcl_CreateObjCommand(interp, "c++ trampoline1402", trampoline1402, 0, NULL);
}
newInterpreterImplPost(interp);
invokingInterpreter=master;
return interp; }
