/**
 * @file
 * @author Generated by a script by Jason Lingle
 * @brief Declares trampoline functions used by src/tcl_iface/dynfun.hxx
 */

static R tramp0(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[0]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp1(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[1]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp2(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[2]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp3(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[3]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp4(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[4]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp5(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[5]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp6(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[6]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp7(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[7]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp8(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[8]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp9(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[9]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp10(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[10]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp11(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[11]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp12(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[12]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp13(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[13]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp14(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[14]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

static R tramp15(
  #undef CURR_ARG
  #define CURR_ARG 0
  #define DECLARE_FUNCTION_ARGUMENTS
  #include "dynfun.hxx"
  ) { return impls[15]->invoke(
    #undef CURR_ARG
    #define CURR_ARG 0
    #define LIST_FUNCTION_ARGUMENTS
    #include "dynfun.hxx"
    ); }

